Layout/EmptyLinesAroundBlockBody:
  Enabled: false
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines
Metrics/MethodLength:
  Max: 16
Style/StringLiterals:
  EnforcedStyle: double_quotes
