#! /usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path("../lib", __dir__)

require "swa/cli/main_command"

$stdout.sync = true
$stderr.sync = true

Swa::CLI::MainCommand.run
